name       : glslang
version    : 8.13.3743
release    : 16
source     :
    - https://github.com/KhronosGroup/glslang/archive/8.13.3743.tar.gz : 639ebec56f1a7402f2fa094469a5ddea1eceecfaf2e9efe361376a0f73a7ee2f
license    : BSD-3-Clause
component  : xorg.display
emul32     : yes
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
patterns   :
    - 32bit-devel : /usr/lib32/cmake
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
