name       : glslang
version    : 7.11.3188
release    : 11
source     :
    - git|https://github.com/KhronosGroup/glslang.git : 2d0095f2fd23120b32c2ad73e3a0b6cac776f257
license    : BSD-3-Clause
component  : xorg.display
libsplit   : no
emul32     : yes
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
setup      : |
    %patch -p1 < $pkgfiles/glslang_tests.patch
    %patch -p1 < $pkgfiles/fix-hack.patch

    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    cd Test
    ./runtests
