name       : glslang
version    : 8.13.3727
release    : 15
source     :
    - git|https://github.com/KhronosGroup/glslang.git : e157435c1e777aa1052f446dafed162b4a722e03
license    : BSD-3-Clause
component  : xorg.display
emul32     : yes
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
patterns   :
    - 32bit-devel : /usr/lib32/cmake
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
