name       : glslang
version    : 11.0.0
release    : 18
source     :
    - git|https://github.com/KhronosGroup/glslang.git : c594de23cdd790d64ad5f9c8b059baae0ee2941d
license    : BSD-3-Clause
component  : xorg.display
emul32     : yes
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
patterns   :
    - 32bit-devel : /usr/lib32/cmake
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
