name       : glslang
version    : 3.0.0
release    : 3
source     :
    - git|https://github.com/KhronosGroup/glslang.git : a4a4d5e22c375d37bd286106904ef819eafff29b
license    : MIT
component  : xorg.graphics
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
builddeps  :
    - bison
libsplit   : no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
