name       : glslang
version    : 3.0.0
release    : 2
source     :
    - https://git.solus-project.com/projects/glslang/snapshot/glslang-a4a4d5e22c375d37bd286106904ef819eafff29b.tar.gz : 9c12c63266a7274c8dfe80fb7fb4b5f548023160eecb2a5b56d92a7ef3c4e098
license    : MIT
component  : xorg.graphics
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
builddeps  :
    - bison
libsplit   : no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
