name       : glslang
version    : 7.10.2984
release    : 9
source     :
    - git|https://github.com/KhronosGroup/glslang.git : 7.10.2984
license    : BSD-3-Clause
component  : xorg.display
libsplit   : no
emul32     : yes
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
setup      : |
    %patch -p1 < $pkgfiles/glslang_tests.patch

    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
# See: https://github.com/KhronosGroup/glslang/issues/1585
#check      : |
#    cd Test
#    ./runtests
