name       : glslang
version    : 5.1
release    : 6
source     :
    - git|https://github.com/KhronosGroup/glslang.git : 097047a919be0bdebe106e8de593697dada054c5
license    : MIT
component  : xorg.graphics
libsplit   : no
emul32     : yes
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
setup      : |
    %patch -p1 < $pkgfiles/glslang_tests.patch

    mkdir solusBuildDir && cd solusBuildDir
    %cmake -DCMAKE_INSTALL_LIBDIR=%libdir% \
           -GNinja ..
build      : |
    %meson_build
install    : |
    %meson_install
check      : |
    cd Test
    ./runtests
