name       : glslang
version    : 11.9.0
release    : 24
source     :
    - git|https://github.com/KhronosGroup/glslang.git : sdk-1.3.204.1
license    : BSD-3-Clause
component  : xorg.display
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
patterns   :
    - 32bit-devel : /usr/lib32/cmake
emul32     : yes
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir% -DBUILD_SHARED_LIBS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
