name       : glslang
version    : 3.20
release    : 5
source     :
    - git|https://github.com/KhronosGroup/glslang.git : 82ead04c39c6a4b7fa153d692b26181091c43c15
license    : MIT
component  : xorg.graphics
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
builddeps  :
    - bison
libsplit   : no
emul32     : yes
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        mv $installdir/usr/lib $installdir/usr/lib32
    else
        mv $installdir/usr/lib $installdir/usr/lib64
    fi
