name       : glslang
version    : 11.0.0
release    : 17
source     :
    - https://github.com/KhronosGroup/glslang/archive/SDK-candidate-26-Jul-2020.tar.gz : 5667f8f4fbf3dad21af3a48335813a41b9260e9268e287c9c451556b710bac4d
license    : BSD-3-Clause
component  : xorg.display
emul32     : yes
summary    : Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
description: |
    Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator
patterns   :
    - 32bit-devel : /usr/lib32/cmake
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
